site_name: My Notes

nav:
  - Home: index.md
  - Chapter 1:
      - Introduction : 1_chapter/1_lesson.md
  - Chapter 2:
      - Introduction : 2_chapter/1_lesson.md
  - Chapter 3:
      - Introduction : 3_chapter/1_lesson.md

copyright: Site developed and maintained by <a href="https://abhigupta.io">Abhinav Gupta</a>
extra_css:
  - css/custom.css
  
theme:
  name: readthedocs
  highlightjs: true
  logo: img/logo.svg

plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


