[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "glacier"
authors = [{name = "Abhinav Gupta", email = "iitrabhi@gmail.com"}]
dynamic = ["version", "description"]
